package core_java;

public class Exception_Demo
{

	public static void main(String[] args) 
	{ 
		int x,y,z;
		x=10;
		y=0;
		try {
		z=x/y;
		System.out.println(z);
		}
		catch(Exception e)
		{
			System.out.println(e);
			
		}
		
		
		
		

	}

}
